### ISSUE TITLE
PROJECT PLAN

### ISSUE THREAD

**Issue by bailscodesstuff** [bailslearnsstuff/musicTasteAnalysis#2]
This is my general plan for this project as well as what I'm aiming to achieve.

GOAL:
I want to implement the KNN classification algorithm to determine what songs my two friends (Elizabeth and Maya) will like. 
I will analyse their own playlists as training and validation data and use the generic Spotify playlists as the validation data.

PLAN/ OVERALL TODO LIST:

- [x] watch the knn section of my udemy course
- [x] read chapter 4 of stats learning textbook , UNDERSTAND IT
- [x] make the dataset of E&M's playlist larger (use the api to get more data)
- [x] after implementing KNN , do the same etst with other classification algorithms
- [x] medium article on results of project - outline what most effective algorithm waS

Things to note:
- [x] I don't yet know what generic spotify playlists to use - will they be of a certain genre? mood?

**Comment by bailscodesstuff** [comment]
updates:

KNN implementation is done! I'm gonna try all the classifcation algorithms and see which one is the most accurate

in the meantime I need to: 

- [x] make the data set larger 
- [x] modify code -- all plaulists can be in the same dataset

**Comment by bailscodesstuff** [comment]
ALGORITHMS TO IMPLEMENT 

- [x] KNN
- [x] Logistic Regression
- [x] support vector machines

**Comment by bailscodesstuff** [comment]
points for medium write up:

- KNN
- [x] briefly explain what KNN is 
- [x] explain why data needs to be standardised 
- [ ] elbow method brief explanation

LOG R:
- [x] briefly explain what log r is 
- [ ] why do we not need to standardise log r?

SVM
- [ ] briefly explain what SVM is 
- [x] why is grid search required


extras 
- [x] confusion matrix
- [x] classification reports

**Comment by bailscodesstuff** [comment]
future to do:

- [ ] change usernames to actual names in dataframe
- [ ] create separate files: one for creating dataset one for algorithm implementation - make it look cleaner!
-  [ ] comment code

**Comment by bailscodesstuff** [comment]
FINAL THINGS TO DO - 26/09

- [ ] optimise logR using grid search
- [ ] explain what logR and SVM actually are


ARTICLE
- [ ] classification report of each alg
- [ ] show another metric - ROC curves
- [ ] show how best performing alg was optimised, explain how others were optimised
